//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public string Codigo { get; set; }
        public string Cliente { get; set; }
        public string Habitacion { get; set; }
        public System.DateTime Fecha_Entrada { get; set; }
        public System.DateTime Fecha_Salida { get; set; }
        public decimal Monto_Total { get; set; }
        public string Usuario { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Habitacion Habitacion1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
